services:
  haggle-calculator:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1339:80"
    volumes:
      - $PWD/conf:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: